### ISSUE TITLE
CreateExpense Functionality

### ISSUE THREAD

**Issue by namaggarwal** [namaggarwal/splitwise#4]
A method to create a new expense on splitwise.

**Comment by sloppycoffee** [comment]
I think most of the code I wrote can be pulled right over. Its just getting the __makePostRequest to actually work... I believe the options dictionary just needs to be turned into json with json.dump(options). Then again, I didn't get it working.. Whatever is going to work. I am interested in seeing your solution.

**Comment by sloppycoffee** [comment]
I got a reply from the Splitwise API team, which I think will help, especially since I didn't realize the first arg was a boliean.

Sorry for the slow reply! Happy to help explain – I know our documentation is pretty rough around the edges. (Hopefully I get a chance to clean it up sometime soon, but we're a tiny company, so it hasn't made it to the top of the todo list yet.)

"payment" is a boolean value to determine whether the transaction should be considered an expense or a payment. The reason this value is required is because certain types of transactions are mathematically equivalent. For example, paying a friend $20 is mathematically equivalent to getting a $20 IOU from a friend – either one makes your friend's balance go down by $20. On Splitwise, those two transactions would look virtually identical other than the "payment" field being true or false.

Note that you'll also need to include more details about the actual bill split and who's involved. For example, if I wanted to add a $20 bill paid by me and split between the two of us, I'd include the following parameters:

users__0__user_id = MY_USER_ID
users__0__paid_share = 20
users__0__owed_share = 10
users__1__user_id = YOUR_USER_ID
users__1__owed_share = 10

Alternately, you could pass "users__0__email" instead of "users__0__user_id", and Splitwise will automatically find the user for that email address (or Splitwise will send an invite to that person if they're not already on Splitwise).

Beyond that, a good way to see what you should provide to create_expense is to call get_expense on an existing expense, and examine its attributes. That should give you a decent example of how the various fields are used. If you have any further questions, though, just let me know and I'll get back to you as soon as I'm able.

Hope that helps! Let me know if you have any more issues, and have a great day.

Cheers,
-Ryan

**Comment by sloppycoffee** [comment]
Were you take a look at this issue yet? Anything I can help with?

**Comment by namaggarwal** [comment]
Hi,

I have a rough idea on how to do this. Will do this on the weekend. 

Naman

**Comment by sloppycoffee** [comment]
Hey Naman,

I am wrapping up my project and everything is looking great. I got everything working and tested except the final part, which is adding the expense to splitwise. Were you able to look into that yet?

**Comment by namaggarwal** [comment]
Hi,

I wrote some code but haven't tested it due to my hectic day job. I will try to do it this week :)

Naman

**Comment by sloppycoffee** [comment]
Great! That's good news! Looking forward to pulling in your changes. Thanks
for the hard work.

**Comment by sloppycoffee** [comment]
Were you able to look at this during the week? You could also check in your changes and I could test them. Let me know.

**Comment by sloppycoffee** [comment]
Hate to bug you again but this weekend would be a great weekend for me to finish up this project. Let me know if there is anything I can do.

**Comment by namaggarwal** [comment]
Hi Ryan

Apologies for the late reply. I am on my annual vacation and is not able to work on this for some time.

Naman

**Comment by sloppycoffee** [comment]
Any update? Very much looking on finishing up and getting my project into production.

**Comment by namaggarwal** [comment]
I will do it this weekend.

**Comment by sloppycoffee** [comment]
Any update?

**Comment by namaggarwal** [comment]
Hey Ryan

Apologies for late reply. I have completed the code, however, its throwing some error. I cannot figure out why. I have dropped an email to Splitwise team to figure out the error.

If you want I can give you the access to the code. 

In short I am sending a request with following data

users_1_owed_share=2.0&users_1_user_id=79774&creation_method=unequal&users_1_paid_share=10.00&cost=10&users_2_paid_share=0.00&users_2_owed_share=8.00&users_2_user_id=281236&group_id=0&currency_code=SGD&description=Testing

And the response I am getting is - 

{"expenses":[],"errors":{"base":["An unknown error occured. Please try again or contact support@splitwise.com if you experience repeated issues. Sorry for the trouble!"]}}

**Comment by namaggarwal** [comment]
Hi, 

I found and fixed the issue. A new release has been made with this functionality. Splitwise-0.0.5

**Comment by sloppycoffee** [comment]
Thanks for getting that checked in. I pulled in your changes and testing them now. Will report if I find issues.

**Comment by sloppycoffee** [comment]
I am getting the same error message. What did you do to fix it?

**Comment by sloppycoffee** [comment]
I found your solution on the splitwise api about the extra underscore. Don't think that is my problem. Did you have to provide "payment" as part of the api call? I am not seeing that in your code changes but is required, according to the api documentation.

**Comment by sloppycoffee** [comment]
Nevermind. Talked to the API support team, and the API doesn't support what I want to do.

**Comment by sloppycoffee** [comment]
I am getting this error message:

    user1 = ExpenseUser()
NameError: name 'ExpenseUser' is not defined

Not sure why. I updated to latest version. 

Is it related to this?

from splitwise import Splitwise
from splitwise.expense import Expense

**Comment by sloppycoffee** [comment]
Well, I added this.. Seemed to get around the error.. Not sure if that was what I should have done or not..

from splitwise.expense import ExpenseUser

**Comment by sloppycoffee** [comment]
I think I got. Thanks for all the work! 

What is your bitcoin address? Ill donate some coin for all your hard work!

**Comment by namaggarwal** [comment]
Hey Ryan,

 I am so happy that my work was helpful to you. I have fixed the documentation for create expense. I have also updated my donation info in Readme.md. Thank you so much for the support. This encouraged me to do more open source work.

Naman

**Comment by mvsreejithfrnds** [comment]
I have been trying to create and expense entry in splitwise from my application using splitwise API (https://secure.splitwise.com/api/v3.0/create_expense). 

Authentication : OAuth1.0

Request

API: create_expense
request body:
{
payment:false,
cost: 100.00,
description:”test”,
users__0__user_id: current user id,
users__0__paid_share:100.00,
users__0__owed_share:50.00,
users__1__user_id:friend user id,
users__1__paid_share: 0.00,
users__1__owed_share:50.00
}
Response

create query called successfully got response 200. But the expense is not reflected in the app

**Comment by mvsreejithfrnds** [comment]
Expense create completed without error but not reflected in Splitwise
Api 
create_expense
Request
users__0__owed_share : 75.0
cost : 150.0
users__1__owed_share : 75.0
users__1__user_id : <my user ID>
users__0__paid_share : 0.0
description : "test"
payment : false
users__1__paid_share : 150.0
users__0__user_id : <friend user ID>

Response
Response{code=200, message='OK', body='null', headers={Transfer-Encoding=chunked, null=HTTP/1.1 200 OK, Server=nginx, X-Request-Id=2915a687-0d9b-4e6e-a9f0-18bf835d1dd5, X-Runtime=0.037593, X-Content-Type-Options=nosniff, Connection=keep-alive, Pragma=no-cache, Date=Fri, 03 Jan 2020 23:32:03 GMT, Via=1.1 vegur, Referrer-Policy=origin, X-Frame-Options=SAMEORIGIN, Strict-Transport-Security=max-age=31536000, Cache-Control=no-cache, no-store, max-age=0, must-revalidate, Content-Disposition=inline; filename="response.json", X-Xss-Protection=1; mode=block, Set-Cookie=, Vary=Accept-Encoding, Expires=Fri, 01 Jan 1990 00:00:00 GMT, Content-Type=application/json; charset=utf-8}}
